repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Ou a versão mais recente
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.3.0 # Ou a versão mais recente
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=79]

  - repo: https://github.com/pycqa/isort
    rev: v5.12.0 # Ou a versão mais recente
    hooks:
      - id: isort
        language_version: python3
        args: [--profile=black]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v6.2.0 # Ou a versão mais recente
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-docstrings, flake8-bugbear, flake8-comprehensions]
        language_version: python3
        args: [--max-line-length=79]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950 # Ou a versão mais recente
    hooks:
      - id: mypy
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5 # Ou a versão mais recente
    hooks:
      - id: pylint
        language_version: python3
        additional_dependencies: [pylint-django]
