# Generated by Django 5.0.7 on 2024-07-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
